name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (x.y.z-abcN e.g. 4.5.6-beta1)'
        required: true
      real_op:
        description: 'Do the real work, not just preview'
        type: boolean
        default: false
        required: true
    

jobs:
  preparation:
    runs-on: ubuntu-latest

    steps:
      - name: Check for admin-ui-assets tag
        if: github.event.repository.name == 'oss'
        uses: octokit/request-action@v2.x
        with:
          owner: ibexa
          repo: admin-ui-assets
          route: /repos/{owner}/{repo}/contents/package.json?ref=v${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
  
  action:
    needs: preparation
    runs-on: ubuntu-latest
    
    steps:
      - name: Install sponge
        run: |
          sudo apt-get install -y moreutils

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          extensions: pdo_sqlite, gd
          tools: cs2pr

      - uses: actions/checkout@v3

      - name: Get release information
        uses: octokit/request-action@v2.x
        id: release
        with:
          owner: ibexa
          repo: release-maker
          route: /repos/{owner}/{repo}/contents/releases/${{ inputs.version }}/release.json
        env:
          GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}

      - name: Process release information
        run: |
          cat > input.json <<'EOF'
          ${{ steps.release.outputs.data }}
          EOF
          jq -r '.["content"]' input.json | base64 --decode | jq -c . > release.json
          jq -s '[ .[][] | { (.packageName): (.targetVersion) } ] | add' release.json | sponge release.json

      - name: Set minimum stability
        run: |
          VERSION=$( echo ${{ inputs.version }} | cut -d '-' -f 2 )
          SET_STABILITY="composer config minimum-stability"
          case $VERSION in:
            alpha*) $SET_STABILITY alpha ;;
            beta*) $SET_STABILITY beta ;;
            rc*) $SET_STABILITY rc ;;
            *) $SET_STABILITY stable ;;
          esac;
          composer config prefer-stable true

      - name: Patch parent version for OSS
        if: github.event.repository.name == 'oss'
        run: jq '.require["ibexa/admin-ui-assets"] |= "${{ inputs.version }}"' composer.json | sponge composer.json
      - name: Patch parent version for Content
        if: github.event.repository.name == 'content'
        run: jq '.require["ibexa/oss"] |= "${{ inputs.version }}"' composer.json | sponge composer.json
      - name: Patch parent version for Experience
        if: github.event.repository.name == 'experience'
        run: jq '.require["ibexa/content"] |= "${{ inputs.version }}"' composer.json | sponge composer.json
      - name: Patch parent version for Commerce
        if: github.event.repository.name == 'commerce'
        run: jq '.require["ibexa/experience"] |= "${{ inputs.version }}"' composer.json | sponge composer.json

      - name: Patch composer require versions
        run: |
          jq --argfile release release.json '
            .require |= (
              to_entries | 
              map({
                key: .key,
                value: (if ($release[.key]) then $release[.key] else .value end)
              }) | from_entries
            )
          ' composer.json > composer.tmp
          mv composer.tmp composer.json

      - name: Reformat composer.json
        run: cat composer.json | unexpand -t2 | expand -t4 | sponge composer.json

      - name: debug composer.json
        run: cat composer.json

      - name: Add composer keys for private packagist
        run: |
          composer config http-basic.updates.ibexa.co $SATIS_NETWORK_KEY $SATIS_NETWORK_TOKEN
          composer config github-oauth.github.com $TRAVIS_GITHUB_TOKEN
        env:
          SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
          SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
          TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}

      - name: Composer update
        run: |
          composer update --no-scripts --no-plugins --no-install

      - name: Commit and tag
        if: inputs.real_op
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add composer.*
          git commit -m "[composer] Set dependencies for ${{ inputs.version }} release + .lock"
          git tag "v${{ inputs.version }}"

      - name: Push changes
        if: inputs.real_op
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.version }}
          tags: true
