name: Call Create Release for tag Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release_for_tag:
    uses: ibexa/gh-workflows/.github/workflows/release.yml@IBX-5569
    secrets: inherit
